blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/afri-bit/vsconan/issues/new?template=bug_report.yml
    about: Report a bug to help improve the project.
